// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZAXnF2CMoAyT07Pow2W-ilXjFEOUw7Zo',
    appId: '1:138221435738:web:9b810734f6070294f7d163',
    messagingSenderId: '138221435738',
    projectId: 'mynotes-pinhasdev',
    authDomain: 'mynotes-pinhasdev.firebaseapp.com',
    storageBucket: 'mynotes-pinhasdev.appspot.com',
    measurementId: 'G-SJ2STL14ZX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgbOdSqTMyTOhdjFSWH7KCx0mi8quwDjI',
    appId: '1:138221435738:android:9305dc6143e37b56f7d163',
    messagingSenderId: '138221435738',
    projectId: 'mynotes-pinhasdev',
    storageBucket: 'mynotes-pinhasdev.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApruyIMavJrDaaYMdPgSZ0XVlhTs430Ck',
    appId: '1:138221435738:ios:dd1cc8493d45d1a5f7d163',
    messagingSenderId: '138221435738',
    projectId: 'mynotes-pinhasdev',
    storageBucket: 'mynotes-pinhasdev.appspot.com',
    iosClientId: '138221435738-g0fc5b3f937v7pe0kl1t9sfm5i34esnf.apps.googleusercontent.com',
    iosBundleId: 'pt.foodbus.mynotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyApruyIMavJrDaaYMdPgSZ0XVlhTs430Ck',
    appId: '1:138221435738:ios:dd1cc8493d45d1a5f7d163',
    messagingSenderId: '138221435738',
    projectId: 'mynotes-pinhasdev',
    storageBucket: 'mynotes-pinhasdev.appspot.com',
    iosClientId: '138221435738-g0fc5b3f937v7pe0kl1t9sfm5i34esnf.apps.googleusercontent.com',
    iosBundleId: 'pt.foodbus.mynotes',
  );
}
